---
- name:  "Install and configure controller node - configure prerequisites"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  environment:
    OS_TOKEN: "{{ config.keystone_os_token }}"
    OS_URL: "{{ config.keystone_os_url }}"
  tasks:
    - name: Create the nova database
      mysql_db: 
        login_user: "{{ config.mysql_login_user }}"
        login_password: "{{ config.mysql_login_password }}"
        name: nova
        state: present

    - name: Grant proper access to the nova database
      mysql_user: 
        login_user: "{{ config.mysql_login_user }}"
        login_password: "{{ config.mysql_login_password }}"
        name: nova 
        host: "{{ item }}" 
        password: "{{ config.nova_mysql_password }}" 
        priv: nova.*:ALL
      with_items:
        - "%"
        - localhost

    - name: Delete the nova user if existent
      shell: openstack user delete nova || true

    - name: Create the nova user
      shell: "openstack user create --password {{ config.nova_user_password }} nova"

    - name: Add the admin role to the nova user
      shell: "openstack role add --project service --user nova admin"

    - name: Create the nova service entity
      shell: "openstack service create --name nova --description 'OpenStack Compute' compute"

    - name: Create the Compute service API endpoint
      shell: 'openstack endpoint create --publicurl http://{{ config.controller_node_hostname }}:8774/v2/%\(tenant_id\)s --internalurl http://{{ config.controller_node_hostname }}:8774/v2/%\(tenant_id\)s --adminurl http://{{ config.controller_node_hostname }}:8774/v2/%\(tenant_id\)s --region RegionOne compute'
