---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_nova.html
- include: 01_configure_prerequisites.yml
- include: 02_Install_and_configure_Compute_controller_components.yml
- include: 03_finalize_installation.yml
- include: 04_Install_and_configure_a_compute_node.yml
- include: 05_finalize_installation.yml