---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-network-node.html
- include: 01_configure_prerequisites.yml
- include: 02_install_the_Networking_components.yml
- include: 03_configure_the_Networking_common_components.yml
- include: 04_configure_the_Modular_Layer_2_plug-in.yml
- include: 05_configure_the_Layer-3_agent.yml
- include: 06_configure_the_DHCP_agent.yml
- include: 07_configure_the_metadata_agent.yml
- include: 08_configure_the_Open_vSwitch_service.yml
- include: 09_finalize_installation.yml
- include: 10_Verify_operation

