---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/keystone-install.html

# Add the Identity service > Install and configure > configure the Apache HTTP server

- name: 1. Restart the Apache HTTP server
  service: 
    name: apache2
    state: restarted

- name: 2. Because this configuration uses a SQL database server, you can remove the SQLite database file
  shell: rm -f /var/lib/keystone/keystone.db
