---
- name: generate host files
  hosts: localhost:all
  sudo: yes
  # ansible should only ask for the sudo password of localhost
  # https://github.com/ansible/ansible/issues/1227
  # start this with --ask-sudo-pass
  # http://stackoverflow.com/questions/21870083/specify-sudo-password-for-ansible
  tasks:

  - name: "remove old hostfile entries"
    lineinfile: 
     dest: /etc/hosts 
     regexp: ".*#autogen_openstack_node" 
     state: absent

  - name: "create new /etc/hosts entries"
    lineinfile: 
     dest: /etc/hosts 
     line: "{{ hostvars[item].ansible_default_ipv4.address }} {{hostvars[item].ansible_hostname}} {{hostvars[item].ansible_fqdn}} #autogen_openstack_node" 
     state: present
    when: hostvars[item].ansible_default_ipv4.address is defined
    # TODO: we would like to exclude localhost here
    with_items: groups['all']

