---
- name: generate host files
  hosts: localhost:all
  sudo: yes
  tasks:

  - name: "remove old hostfile entries"
    lineinfile: 
     dest: /etc/hosts 
     regexp: ".*#autogen_openstack_node" 
     state: absent

  - name: "create new /etc/hosts entries"
    lineinfile: 
     dest: /etc/hosts 
     line: "{{ hostvars[item].ansible_default_ipv4.address }} {{hostvars[item].ansible_hostname}} {{hostvars[item].ansible_fqdn}} #autogen_openstack_node" 
     state: present
    when: hostvars[item].ansible_default_ipv4.address is defined
    #TODO: we would like to exclude localhost here
    with_items: groups['all']

