---
- hosts: all
# see https://github.com/ansible/ansible/issues/4355#issuecomment-25623433
# for sudo: yes
  sudo: yes
  gather_facts: False
  tasks:
  - name: update the cache
    apt:       
      update_cache: yes
  - name: install cloud keyring
    apt: 
      pkg: ubuntu-cloud-keyring 
      state: installed 
  - name: add repository
    lineinfile:
      dest: /etc/apt/sources.list.d/cloudarchive-kilo.list
      create: yes
      line: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/kilo main"
  - name: finalize installation
    apt:
      update_cache: yes
  - name: upgrade the distribution
    apt: 
      upgrade: dist

