---
- hosts: all
# see https://github.com/ansible/ansible/issues/4355#issuecomment-25623433
# for sudo: yes
  sudo: yes
  roles:
  - config
  tasks:
  - name: install the message queue service
    apt: 
      pkg: rabbitmq-server
      state: installed 
  - name: configure the message queue service #1 setting password
    shell: "rabbitmqctl add_user openstack {{ config.rabbitmq_password }}"
    
  
# this playbook was created according to
# http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_basic_environment.html
