---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/glance-install.html
- include: 01_configure_prerequisites.yml
- include: 02_Install_and_configure_the_Image_service_components.yml
- include: 03_finalize_installation.yml
- include: 04_verify_operation.yml
