---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron_initial-tenant-network.html
- name:  "Add a networking component > Create initial networks > Create tenant networks"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  environment: "{{ config.environment.demo }}"

  tasks:
  - name: "1.2 Create the tenant network"
    shell: "source {{ ansible_user_dir}}/admin-openrc.sh && neutron net-create demo-net"
    args:
      executable: /bin/bash

  - name: "2. Create a subnet on the tenant network"
    shell: "source {{ ansible_user_dir}}/admin-openrc.sh && neutron subnet-create demo-net {{ config.tenant_network_cidr }} --name demo-subnet --gateway {{ config.tenant_network_gateway }}"
    args:
      executable: /bin/bash

  - name: "3.1 Create a router on the tenant network and attach the external and tenant networks to it"
    shell: "source {{ ansible_user_dir}}/admin-openrc.sh && neutron router-create demo-router"
    args:
      executable: /bin/bash

  - name: "3.2 Attach the router to the demo tenant subnet"
    shell: "source {{ ansible_user_dir}}/admin-openrc.sh && neutron router-interface-add demo-router demo-subnet"
    args:
      executable: /bin/bash

  - name: "3.3 Attach the router to the external network by setting it as the gateway"
    shell: "source {{ ansible_user_dir}}/admin-openrc.sh && neutron router-gateway-set demo-router ext-net"
    args:
      executable: /bin/bash
