---
- name:  "Controller - Install and configure controller node - configure prerequisites"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  environment: config.environment.token

  tasks:
    - name: Create the neutron database
      mysql_db: 
        login_user: "{{ config.mysql_login_user }}"
        login_password: "{{ config.mysql_login_password }}"
        name: neutron
        state: present

    - name: Grant proper access to the neutron database
      mysql_user: 
        login_user: "{{ config.mysql_login_user }}"
        login_password: "{{ config.mysql_login_password }}"
        name: neutron 
        host: "{{ item }}" 
        password: "{{ config.neutron_mysql_password }}" 
        priv: neutron.*:ALL
      with_items:
        - "%"
        - localhost

    - name: Delete the neutron user if existent
      shell: openstack user delete neutron || true

    - name: Create the neutron user
      shell: "openstack user create --password {{ config.neutron_user_password }} neutron"

    - name: Add the admin role to the neutron user
      shell: "openstack role add --project service --user neutron admin"

    - name: Create the neutron service entity
      shell: "openstack service create --name neutron --description 'OpenStack Networking' network"

    - name: Create the Networking service API endpoint
      shell: 'openstack endpoint create --publicurl http://{{ config.controller_node_hostname }}:9696 --adminurl http://{{ config.controller_node_hostname }}:9696 --internalurl http://{{ config.controller_node_hostname }}:9696 --region RegionOne network'
