---
- name:  "Controller - Finalize Installation"
  hosts: network
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:
  - name: "Restart the Networking services:"
    service: 
      name: "{{ item }}"
      state: restarted
    with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent