---
- name:  "Compute - configure prerequisites"
  hosts: compute
  roles:
    - config
  sudo: True
  gather_facts: False
  environment:
    OS_TOKEN: "{{ config.keystone_os_token }}"
    OS_URL: "{{ config.keystone_os_url }}"
  tasks:
    - name: "Edit the /etc/sysctl.conf file to contain the following parameters"
      lineinfile: 
        dest: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
        create: yes
      with_items:
      - "net.ipv4.conf.all.rp_filter=0"
      - "net.ipv4.conf.default.rp_filter=0"
      - "net.bridge.bridge-nf-call-iptables=1"
      - "net.bridge.bridge-nf-call-ip6tables=1"

    - name: "Implement the changes"
      shell: "sysctl -p"