---
- name:  "Install and configure compute node"
  hosts: compute
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:
    - name: "Install the packages"
      apt: pkg={{item}} state=installed
      with_items:
      - neutron-plugin-ml2
      - neutron-plugin-openvswitch-agent

# To configure the Networking common components
    - name: "Configure the Networking common components - (a) In the [database] section, comment out any connection options because network nodes do not directly access the database"
      ini_file: dest=/etc/neutron/neutron.conf
                section=database
                option="connection"
                state=absent

    - name: "(b) Edit /etc/neutron/neutron.conf [DEFAULT] section"
      ini_file: dest=/etc/neutron/neutron.conf
                section=DEFAULT
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'rpc_backend', value: 'rabbit' }
      - { option: 'auth_strategy', value: 'keystone' }
      - { option: 'core_plugin', value: 'ml2' }
      - { option: 'service_plugins', value: 'router' }
      - { option: 'allow_overlapping_ips', value: 'True' }
      - { option: 'verbose', value: 'True' }

    - name: "(c) Edit /etc/neutron/neutron.conf [oslo_messaging_rabbit] section"
      ini_file: dest=/etc/neutron/neutron.conf
                section=oslo_messaging_rabbit
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'rabbit_host', value: '{{ config.controller_node_hostname }}' }
      - { option: 'rabbit_userid', value: 'openstack' }
      - { option: 'rabbit_password', value: '{{ config.rabbitmq_password }}' }

    - name: "(d) Comment out or remove any other options in the [keystone_authtoken] section."
      ini_file: dest=/etc/neutron/neutron.conf
                section=keystone_authtoken
                state=absent

    - name: "(e) Edit /etc/neutron/neutron.conf [keystone_authtoken] section"
      ini_file: dest=/etc/neutron/neutron.conf
                section=keystone_authtoken
                state=present
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'auth_uri', value: 'http://{{ config.controller_node_hostname }}:5000' }
      - { option: 'auth_url', value: 'http://{{ config.controller_node_hostname }}:35357' }
      - { option: 'auth_plugin', value: 'password' }
      - { option: 'project_domain_id', value: 'default' }
      - { option: 'user_domain_id', value: 'default' }
      - { option: 'project_name', value: 'service' }
      - { option: 'username', value: 'neutron' }
      - { option: 'password', value: '{{ config.neutron_user_password }}' }


# To configure the Modular Layer 2 (ML2) plug-in
    - name: "Configure the Modular Layer 2 (ML2) plug-in - (f) Edit /etc/neutron/plugins/ml2/ml2_conf.ini [ml2] section"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=ml2
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'type_drivers', value: 'flat,vlan,gre,vxlan' }
      - { option: 'tenant_network_types', value: 'gre' }
      - { option: 'mechanism_drivers', value: 'openvswitch' }

    - name: "(h) Edit /etc/neutron/plugins/ml2/ml2_conf.ini [ml2_type_gre] section"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=ml2_type_gre
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'tunnel_id_ranges', value: '1:1000' }

    - name: "(i) Edit /etc/neutron/plugins/ml2/ml2_conf.ini [securitygroup] section"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=securitygroup
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'enable_security_group', value: 'True' }
      - { option: 'enable_ipset', value: 'True' }
      - { option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver' }

    - name: "(j) Edit /etc/neutron/plugins/ml2/ml2_conf.ini [ovs] section"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=ovs
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'local_ip ', value: '{{ config.ip_tunnel_prefix }}.????????????'<<<<<<<<<<<<<TODO>>>>>>>>>>>>>>>

    - name: "(k) Edit /etc/neutron/plugins/ml2/ml2_conf.ini [agent] section"
      ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                section=agent
                option={{ item.option }}
                value={{ item.value }}
                backup=yes
      with_items:
      - { option: 'tunnel_types', value: 'gre' }


# To configure the Open vSwitch (OVS) service



# To configure Compute to use Networking