---
- name:  "Compute - Finalize Installation"
  hosts: compute
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:
  - name: "Restart the Compute and Networking services:"
    service: 
      name: "{{ item }}"
      state: restarted
    with_items:
    - nova-compute
    - neutron-plugin-openvswitch-agent