---
- name:  "Create tenant networks"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  environment:
    OS_PROJECT_DOMAIN_ID: default
    OS_USER_DOMAIN_ID: default
    OS_PROJECT_NAME: demo
    OS_TENANT_NAME: demo
    OS_USERNAME: demo
    OS_PASSWORD: "{{ config.openstack_demo_user_password }}"
    OS_AUTH_URL: "http://{{ config.controller_node_hostname }}:5000/v3"
  tasks:
  - name: "Create the tenant network"
    shell: "neutron net-create demo-net"

  - name: "Create a subnet on the tenant network"
  	shell: "neutron subnet-create demo-net {{ config.tenant_network_cidr }} --name demo-subnet --gateway {{ config.tenant_network_gateway }}"

  - name: "Create a router on the tenant network and attach the external and tenant networks to it"
    shell: "neutron router-create demo-router"

  - name: "Attach the router to the demo tenant subnet"
    shell: "neutron router-interface-add demo-router demo-subnet"

  - name: "Attach the router to the external network by setting it as the gateway"
    shell: "neutron router-gateway-set demo-router ext-net"