---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-controller-node.html
- include: 01_configure_prerequisites.yml
- include: 02_Install_and_configure_controller_node.yml
- include: 03_finalize_installation.yml