---
- name:  "Create external networks"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  environment: config.environment.admin

  tasks:
  - name: "Create the external network"
    shell: "neutron net-create ext-net --router:external --provider:physical_network external --provider:network_type flat"

  - name: "Create a subnet on the external network"
    shell: "neutron subnet-create ext-net {{ config.external_network_cidr }} --name ext-subnet --allocation-pool start={{ config.floating_ip_start }},end={{ config.floating_ip_end }} --disable-dhcp --gateway {{ config.external_network_gateway }}"
