---
- hosts: all
  become: yes
  ignore_errors: yes # these are deletions, if they don't exist, that's fine
   # inverse of network with exclamation mark ! is not yet implemented in ansible iptables module
  tasks:
    - name: Delete unnecessary masquerade tcp
      command: iptables -t nat -D POSTROUTING -s 192.168.102.0/24 ! -d 192.168.102.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
    - name: Delete unnecessary masquerade udp
      command: iptables -t nat -D POSTROUTING -s 192.168.102.0/24 ! -d 192.168.102.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
    - name: Delete unnecessary masquerade
      command: iptables -t nat -D POSTROUTING -s 192.168.102.0/24 ! -d 192.168.102.0/24 -j MASQUERADE


- hosts: all
  become: yes
  tasks:
    - name: Delete reject forward
      iptables: state=absent chain=FORWARD out_interface=br_management jump=REJECT
    - name: Delete reject forward
      iptables: state=absent chain=FORWARD in_interface=br_management jump=REJECT


      # TODO: avoid duplicate iptables rules
    - name: Enable masquerade on region X to enable internet access for openstack VMs
      # TODO: refactor for more than 2 regions, delete the NOT (-d)
      command: iptables -t nat -A POSTROUTING -s {{ region.ip_management_prefix }}.0/24 ! -d 192.168.{{200 + item}}.0/24 -j MASQUERADE
      with_items: "{{ other_region_ids }}"

    - name: Add route to all other regions
      command: route add -net 192.168.{{ 200 + item }}.0 netmask 255.255.255.0 gw 192.168.123.{{ 100 + item }}
      with_items: "{{ other_region_ids }}"




