---
- hosts: all
  sudo: false
  tasks:
    - name: Copy run_experiment.sh
      copy: src=../../run_experiment.sh  dest=~/installation_copy/  mode="u=rwx"
    - name: Copy experiments folder
      copy: src=../../experiments/  dest=~/installation_copy/experiments  mode="u=rwx"
