---
- hosts: all
  tasks:
    - name: Copy install.sh
      copy: src=../../install.sh  dest={{ installation_folder }}/  mode="u=rwx"
    - name: Copy installation folder
      copy: src=../../installation/  dest={{ installation_folder }}/installation  mode="u=rwx"
    - name: Overwrite certain installation scripts
      copy: src={{ item }}  dest={{ installation_folder }}/installation backup=yes  mode="u=rwx"
      with_items:
        - ../installation_changed_files/install.sh
        - ../installation_changed_files/setup_virtual_machines.sh
