--- # equivalent of 'install_tools.sh' and 'install_ansible.sh'
- hosts: localhost:all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - wcstools
        - realpath
        - bzr
        - virt-manager
        - python-pip
        - software-properties-common
        - ansible
        - qemu-kvm
        - virtinst
        - libvirt-bin
    - name: install python packages
      pip: name={{ item }} state=present extra_args=--upgrade
      with_items:
        - Jinja2

