# copied from https://github.com/openstack-ansible/openstack-ansible
# see their license file for license information GGPL
---
- name: Install or verify Keystone database
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:

#    - name: debug
#      debug: msg="config.mysql_login_user {{ config.mysql_login_user }} config.mysql_login_password {{ config.mysql_login_password }}"

    - name: ensure keystone database is present
      mysql_db: 
        login_user: "{{ config.mysql_login_user }}"
        login_password: "{{ config.mysql_login_password }}"
        name: keystone
        state: present

    - name: ensure keystone database user is present
      mysql_user: 
        login_user: "{{ config.mysql_login_user }}"
        login_password: "{{ config.mysql_login_password }}"
        name: keystone 
        host: "{{ item }}" 
        password: "{{ config.keystone_mysql_password }}" 
        priv: keystone.*:ALL
      with_items:
        - "%"
        - localhost
