---
- name: create the service entity and API endpoint
  # http://docs.openstack.org/kilo/install-guide/install/apt/content/keystone-services.html
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  # set the environment variables according to
  #  http://stackoverflow.com/a/27736434/1320237
  # and 
  #  https://github.com/ansible/ansible/pull/8651
  environment: 
    OS_TOKEN: "{{ config.keystone_os_token }}"
    OS_URL: "{{ config.keystone_os_url }}"
  tasks:
  - name: Create the service entity for the Identity service
    shell: openstack service create --name keystone \
                     --description "OpenStack Identity" identity
  - name: Create the Identity service API endpoint
    shell: openstack endpoint create \
                     --publicurl {{ config.identity_public_url }} \
                     --internalurl {{ config.identity_internal_url }} \
                     --adminurl {{ config.identity_admin_url }} \
                     --region RegionOne \
                     identity
      
