---
- name:  "Install and configure storage node components"
  hosts: object
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:
  - name: "Install the packages"
    apt: pkg={{item}} state=installed
    with_items:
    - swift
    - swift-account
    - swift-container
    - swift-object

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=account-server.conf.j2 dest=/etc/swift/account-server.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=container-server.conf.j2 dest=/etc/swift/container-server.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=object-server.conf.j2 dest=/etc/swift/object-server.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=container-reconciler.conf.j2 dest=/etc/swift/container-reconciler.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=object-expirer.conf.j2 dest=/etc/swift/object-expirer.conf owner={{ ansible_user_id }}

  - name: Get the host part of the IP 
    shell: echo {{ inventory_hostname }}
    register: host_ip


# Edit the /etc/swift/account-server.conf file and complete the following actions:
  # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/swift/account-server.conf
              regexp='\[DEFAULT\]'
              replace="[DEFAULT_WORKAROUND]"
              backup=no

  - name: "In the [DEFAULT] section, configure the bind IP address, bind port, user, configuration directory, and mount point directory:"
    ini_file: dest=/etc/swift/account-server.conf
              section=DEFAULT_WORKAROUND
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'bind_ip', value: '{{ config.ip_management_prefix }}.{{ host_ip.stdout.split(''.'')[3] }}' }
    - { option: 'bind_port', value: '6002' }
    - { option: 'user', value: 'swift' }
    - { option: 'swift_dir', value: '/etc/swift' }
    - { option: 'devices', value: '/srv/node' }

  - name: "In the [pipeline:main] section, enable the appropriate modules:"
    ini_file: dest=/etc/swift/account-server.conf
              section='pipeline:main'
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'pipeline', value: 'PIPELINE_REPLACEMENT_STRING' }

  - name: "In the [pipeline:main] section, enable the appropriate modules (Using ansible replace as ini_file does not support spaces in value)"
    replace: dest=/etc/swift/account-server.conf
              regexp='PIPELINE_REPLACEMENT_STRING'
              replace="healthcheck recon account-server"
              backup=no

  - name: "In the [filter:recon] section, configure the recon (metrics) cache directory:"
    ini_file: dest=/etc/swift/account-server.conf
              section='filter:recon'
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'recon_cache_path', value: '/var/cache/swift' }

# WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/swift/account-server.conf
              regexp='\[DEFAULT_WORKAROUND\]'
              replace="[DEFAULT]"
              backup=no


# Edit the /etc/swift/container-server.conf file and complete the following actions:
  # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/swift/container-server.conf
              regexp='\[DEFAULT\]'
              replace="[DEFAULT_WORKAROUND]"
              backup=no

  - name: "In the [DEFAULT] section, configure the bind IP address, bind port, user, configuration directory, and mount point directory:"
    ini_file: dest=/etc/swift/container-server.conf
              section=DEFAULT_WORKAROUND
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'bind_ip', value: '{{ config.ip_management_prefix }}.{{ host_ip.stdout.split(''.'')[3] }}' }
    - { option: 'bind_port', value: '6001' }
    - { option: 'user', value: 'swift' }
    - { option: 'swift_dir', value: '/etc/swift' }
    - { option: 'devices', value: '/srv/node' }

  - name: "In the [pipeline:main] section, enable the appropriate modules:"
    ini_file: dest=/etc/swift/container-server.conf
              section='pipeline:main'
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'pipeline', value: 'PIPELINE_REPLACEMENT_STRING' }

  - name: "In the [pipeline:main] section, enable the appropriate modules (Using ansible replace as ini_file does not support spaces in value)"
    replace: dest=/etc/swift/container-server.conf
              regexp='PIPELINE_REPLACEMENT_STRING'
              replace="healthcheck recon account-server"
              backup=no

  - name: "In the [filter:recon] section, configure the recon (metrics) cache directory:"
    ini_file: dest=/etc/swift/container-server.conf
              section='filter:recon'
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'recon_cache_path', value: '/var/cache/swift' }

# WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/swift/container-server.conf
              regexp='\[DEFAULT_WORKAROUND\]'
              replace="[DEFAULT]"
              backup=no


# Edit the /etc/swift/object-server.conf file and complete the following actions:
  # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/swift/object-server.conf
              regexp='\[DEFAULT\]'
              replace="[DEFAULT_WORKAROUND]"
              backup=no

  - name: "In the [DEFAULT] section, configure the bind IP address, bind port, user, configuration directory, and mount point directory:"
    ini_file: dest=/etc/swift/object-server.conf
              section=DEFAULT_WORKAROUND
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'bind_ip', value: '{{ config.ip_management_prefix }}.{{ host_ip.stdout.split(''.'')[3] }}' }
    - { option: 'bind_port', value: '6000' }
    - { option: 'user', value: 'swift' }
    - { option: 'swift_dir', value: '/etc/swift' }
    - { option: 'devices', value: '/srv/node' }

  - name: "In the [pipeline:main] section, enable the appropriate modules:"
    ini_file: dest=/etc/swift/object-server.conf
              section='pipeline:main'
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'pipeline', value: 'PIPELINE_REPLACEMENT_STRING' }

  - name: "In the [pipeline:main] section, enable the appropriate modules (Using ansible replace as ini_file does not support spaces in value)"
    replace: dest=/etc/swift/object-server.conf
              regexp='PIPELINE_REPLACEMENT_STRING'
              replace="healthcheck recon account-server"
              backup=no

  - name: "In the [filter:recon] section, configure the recon (metrics) cache directory:"
    ini_file: dest=/etc/swift/object-server.conf
              section='filter:recon'
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'recon_cache_path', value: '/var/cache/swift' }
    - { option: 'recon_lock_path ', value: '/var/lock' }

# WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/swift/object-server.conf
              regexp='\[DEFAULT_WORKAROUND\]'
              replace="[DEFAULT]"
              backup=no

  - name: "Ensure proper ownership of the mount point directory structure:"
    shell: "chown -R swift:swift /srv/node"

  - name: "Create the recon directory and ensure proper ownership of it:"
    shell: "mkdir -p /var/cache/swift; chown -R swift:swift /var/cache/swift"