---
- name:  "Object -  Install and configure the storage nodes - configure prerequisites"
  hosts: object
  roles:
    - config
  sudo: True
  gather_facts: False
  environment:
    OS_TOKEN: "{{ config.keystone_os_token }}"
    OS_URL: "{{ config.keystone_os_url }}"
  tasks:
  - name: "Install the supporting utility packages:"
    apt: pkg={{item}} state=installed
    with_items:
    - xfsprogs 
    - rsync

  - name: "Format the /dev/sdb1 and /dev/sdc1 partitions as XFS:"
    shell: "mkfs.xfs /dev/sdb1; mkfs.xfs /dev/sdc1"

  - name: "Create the mount point directory structure:"
    shell: "mkdir -p /srv/node/sdb1; mkdir -p /srv/node/sdc1"

  - name: "Edit the /etc/fstab file and add the following to it:"
    lineinfile:
      dest: /etc/fstab
      create: yes
      line: {{ item }}
    with_items:
    - "/dev/sdb1 /srv/node/sdb1 xfs noatime,nodiratime,nobarrier,logbufs=8 0 2"
    - "/dev/sdc1 /srv/node/sdc1 xfs noatime,nodiratime,nobarrier,logbufs=8 0 2"

  - name: "Mount the devices"
    shell: "mount /srv/node/sdb1; mount /srv/node/sdc1"

  - name: "Edit the /etc/rsyncd.conf file and add the following to it:"
    lineinfile:
      dest: /etc/rsyncd.conf
      create: yes
      line: {{ item }}
    with_items:
    - "/dev/sdb1 /srv/node/sdb1 xfs noatime,nodiratime,nobarrier,logbufs=8 0 2"
    - "/dev/sdc1 /srv/node/sdc1 xfs noatime,nodiratime,nobarrier,logbufs=8 0 2"

  - name: ""
    shell: ""

  - name: ""
    shell: ""
