---
- name:  "Object -  Install and configure the storage nodes - configure prerequisites"
  hosts: object
  roles:
    - config
  sudo: True
  gather_facts: False
  environment:
    OS_TOKEN: "{{ config.keystone_os_token }}"
    OS_URL: "{{ config.keystone_os_url }}"
  tasks:
  - name: "Install the supporting utility packages:"
    apt: pkg={{item}} state=installed
    with_items:
    - xfsprogs 
    - rsync

  - name: "Format the /dev/sdb1 and /dev/sdc1 partitions as XFS:"
    shell: "mkfs.xfs /dev/sdb1; mkfs.xfs /dev/sdc1"

  - name: "Create the mount point directory structure:"
    shell: "mkdir -p /srv/node/sdb1; mkdir -p /srv/node/sdc1"

  - name: "Edit the /etc/fstab file and add the following to it:"
    lineinfile:
      dest: /etc/fstab
      create: yes
      line: "{{ item }}"
    with_items:
    - "/dev/sdb1 /srv/node/sdb1 xfs noatime,nodiratime,nobarrier,logbufs=8 0 2"
    - "/dev/sdc1 /srv/node/sdc1 xfs noatime,nodiratime,nobarrier,logbufs=8 0 2"

  - name: "Mount the devices"
    shell: "mount /srv/node/sdb1; mount /srv/node/sdc1"

  - name: Get the host part of the IP 
    shell: echo {{ inventory_hostname }}
    register: host_ip

  - name: "Edit the /etc/rsyncd.conf file"
    lineinfile:
      dest: /etc/rsyncd.conf
      create: yes
      line: "{{ item }}"
    with_items:
    - "uid = swift"
    - "gid = swift"
    - "log file = /var/log/rsyncd.log"
    - "pid file = /var/run/rsyncd.pid"
    - "address = {{ config.ip_management_prefix }}.{{ host_ip.stdout.split(''.'')[3] }}"

  - name: "Edit [account] section in the /etc/rsyncd.conf file"
    ini_file: dest=/etc/rsyncd.conf
              section=account
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'max connections', value: '2' }
    - { option: 'path', value: '/srv/node/' }
    - { option: 'read only', value: 'false' }
    - { option: 'lock file', value: '/var/lock/account.lock' }

  - name: "Edit [container] section in the /etc/rsyncd.conf file"
    ini_file: dest=/etc/rsyncd.conf
              section=container
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'max connections', value: '2' }
    - { option: 'path', value: '/srv/node/' }
    - { option: 'read only', value: 'false' }
    - { option: 'lock file', value: '/var/lock/container.lock' }

  - name: "Edit [object] section in the /etc/rsyncd.conf file"
    ini_file: dest=/etc/rsyncd.conf
              section=object
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'max connections' value: '2' }
    - { option: 'path' value: '/srv/node/' }
    - { option: 'read only' value: 'false' }
    - { option: 'lock file' value: '/var/lock/object.lock' }

  - name: "Edit the /etc/default/rsync file and enable the rsync service:"
    lineinfile:
      dest: /etc/default/rsync
      create: yes
      line: "{{ item }}"
    with_items:
    - "RSYNC_ENABLE=true"
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>MAKE SURE rsyncd.conf IS WRITTEN CORRECTLY

  - name: "Start the rsync service:"
    service: 
      name: "{{ item }}"
      state: restarted
    with_items:
    - rsync 

